package com.hotel.controller;

public class Pais {

    public enum Country {
        ZAF("ZAF", "ZA", "África do Sul"),
        DEU("DEU", "DE", "Alemanha"),
        ARG("ARG", "AR", "Argentina"),
        AUS("AUS", "AU", "Austrália"),
        BOL("BOL", "BO", "Bolívia"),
        BRA("BRA", "BR", "Brasil"),
        CAN("CAN", "CA", "Canadá"),
        CHL("CHL", "CL", "Chile"),
        CHN("CHN", "CN", "China"),
        COL("COL", "CO", "Colômbia"),
        CRI("CRI", "CR", "Costa Rica"),
        HRV("HRV", "HR", "Croácia"),
        CUB("CUB", "CU", "Cuba"),
        DNK("DNK", "DK", "Dinamarca"),
        EGY("EGY", "EG", "Egito"),
        ECU("ECU", "EC", "Equador"),
        ESP("ESP", "ES", "Espanha"),
        USA("USA", "US", "Estados Unidos"),
        FRA("FRA", "FR", "França"),
        NLD("NLD", "NL", "Holanda"),
        IND("IND", "IN", "índia"),
        ITA("ITA", "IT", "Itália"),
        JAM("JAM", "JM", "Jamaica"),
        JPN("JPN", "JP", "Japão"),
        PER("PER", "PE", "Peru"),
        PRI("PRI", "PR", "Porto Rico"),
        PRT("PRT", "PT", "Portugal"),
        RUS("RUS", "RU", "Rússia"),
        UKR("UKR", "UA", "Ucrânia"),
        URY("URY", "UY", "Uruguai"),
        VEN("VEN", "VE", "Venezuela"),
        AFG("AFG", "AF", "Afeganistão"),
        ALB("ALB", "AL", "Albânia"),
        AND("AND", "AD", "Andorra"),
        AGO("AGO", "AO", "Angola"),
        AIA("AIA", "AI", "Anguilla"),
        ATA("ATA", "AQ", "Antártida"),
        SAU("SAU", "SA", "Arábia Saudita"),
        DZA("DZA", "DZ", "Argélia"),
        ARM("ARM", "AM", "Armênia"),
        ABW("ABW", "AW", "Aruba"),
        AUT("AUT", "AT", "Áustria"),
        AZE("AZE", "AZ", "Azerbaijão"),
        BEL("BEL", "BE", "Bélgica"),
        BHS("BHS", "BS", "Bahamas"),
        BHR("BHR", "BH", "Bahrein"),
        BGD("BGD", "BD", "Bangladesh"),
        BRB("BRB", "BB", "Barbados"),
        BLR("BLR", "BY", "Belarus"),
        BLZ("BLZ", "BZ", "Belize"),
        BEN("BEN", "BJ", "Benin"),
        BMU("BMU", "BM", "Bermudas"),
        BIH("BIH", "BA", "Bósnia-Herzegóvina"),
        BWA("BWA", "BW", "Botsuana"),
        BRN("BRN", "BN", "Brunei"),
        BGR("BGR", "BG", "Bulgária"),
        BFA("BFA", "BF", "Burkina Fasso"),
        BDI("BDI", "BI", "Burundi"),
        BTN("BTN", "BT", "Butão"),
        CPV("CPV", "CV", "Cabo Verde"),
        CMR("CMR", "CM", "Camarões"),
        KHM("KHM", "KH", "Camboja"),
        KAZ("KAZ", "KZ", "Cazaquistão"),
        TCD("TCD", "TD", "Chade"),
        CYP("CYP", "CY", "Chipre"),
        SGP("SGP", "SG", "Cingapura"),
        COG("COG", "CG", "Congo"),
        PRK("PRK", "KP", "Coréia do Norte"),
        KOR("KOR", "KR", "Coréia do Sul"),
        CIV("CIV", "CI", "Costa do Marfim"),
        DJI("DJI", "DJ", "Djibuti"),
        DMA("DMA", "DM", "Dominica"),
        SLV("SLV", "SV", "El Salvador"),
        ARE("ARE", "AE", "Emirados Árabes Unidos"),
        ERI("ERI", "ER", "Eritréia"),
        SVK("SVK", "SK", "Eslováquia"),
        SVN("SVN", "SI", "Eslovênia"),
        EST("EST", "EE", "Estônia"),
        ETH("ETH", "ET", "Etiópia"),
        FJI("FJI", "FJ", "Fiji"),
        PHL("PHL", "PH", "Filipinas"),
        FIN("FIN", "FI", "Finlândia"),
        GAB("GAB", "GA", "Gabão"),
        GMB("GMB", "GM", "Gâmbia"),
        GHA("GHA", "GH", "Gana"),
        GEO("GEO", "GE", "Geórgia"),
        GIB("GIB", "GI", "Gibraltar"),
        GBR("GBR", "GB", "Grã-Bretanha"),
        GRD("GRD", "GD", "Granada"),
        GRC("GRC", "GR", "Grécia"),
        GRL("GRL", "GL", "Groelândia"),
        GLP("GLP", "GP", "Guadalupe"),
        GTM("GTM", "GT", "Guatemala"),
        GGY("GGY", "G", "Guernsey"),
        GUY("GUY", "GY", "Guiana"),
        GUF("GUF", "GF", "Guiana Francesa"),
        GIN("GIN", "GN", "Guiné"),
        GNQ("GNQ", "GQ", "Guiné Equatorial"),
        GNB("GNB", "GW", "Guiné-Bissau"),
        HTI("HTI", "HT", "Haiti"),
        HND("HND", "HN", "Honduras"),
        HKG("HKG", "HK", "Hong Kong"),
        HUN("HUN", "HU", "Hungria"),
        YEM("YEM", "YE", "Iêmen"),
        IDN("IDN", "ID", "Indonésia"),
        IRN("IRN", "IR", "Irã"),
        IRQ("IRQ", "IQ", "Iraque"),
        IRL("IRL", "IE", "Irlanda"),
        ISL("ISL", "IS", "Islândia"),
        ISR("ISR", "IL", "Israel"),
        IMN("IMN", "IM", "Ilha do Homem"),
        CXR("CXR", "CX", "Ilha Natal"),
        PCN("PCN", "PN", "Ilha Pitcairn"),
        REU("REU", "RE", "Ilha Reunião"),
        ALA("ALA", "AX", "Ilhas Aland"),
        CYM("CYM", "KY", "Ilhas Cayman"),
        CCK("CCK", "CC", "Ilhas Cocos"),
        COM("COM", "KM", "Ilhas Comores"),
        COK("COK", "CK", "Ilhas Cook"),
        JEY("JEY", "JE", "Jersey"),
        JOR("JOR", "JO", "Jordânia"),
        KEN("KEN", "KE", "Kênia"),
        KIR("KIR", "KI", "Kiribati"),
        KWT("KWT", "KW", "Kuait"),
        LAO("LAO", "LA", "Laos"),
        LVA("LVA", "LV", "Látvia"),
        LSO("LSO", "LS", "Lesoto"),
        LBN("LBN", "LB", "Líbano"),
        LBR("LBR", "LR", "Libéria"),
        LBY("LBY", "LY", "Líbia"),
        LIE("LIE", "LI", "Liechtenstein"),
        LTU("LTU", "LT", "Lituânia"),
        LUX("LUX", "LU", "Luxemburgo"),
        MAC("MAC", "MO", "Macau"),
        MKD("MKD", "MK", "Macedônia"),
        MDG("MDG", "MG", "Madagascar"),
        MYS("MYS", "MY", "Malásia"),
        MWI("MWI", "MW", "Malaui"),
        MDV("MDV", "MV", "Maldivas"),
        MLI("MLI", "ML", "Mali"),
        MLT("MLT", "MT", "Malta"),
        MAR("MAR", "MA", "Marrocos"),
        MTQ("MTQ", "MQ", "Martinica"),
        MUS("MUS", "MU", "Maurício"),
        MRT("MRT", "MR", "Mauritânia"),
        MYT("MYT", "YT", "Mayotte"),
        MEX("MEX", "MX", "México"),
        FSM("FSM", "FM", "Micronésia"),
        MOZ("MOZ", "MZ", "Moçambique"),
        MDA("MDA", "MD", "Moldova"),
        MCO("MCO", "MC", "Mônaco"),
        MNG("MNG", "MN", "Mongólia"),
        MNE("MNE", "ME", "Montenegro"),
        MSR("MSR", "MS", "Montserrat"),
        MMR("MMR", "MM", "Myanma"),
        NAM("NAM", "NA", "Namíbia"),
        NRU("NRU", "NR", "Nauru"),
        NPL("NPL", "NP", "Nepal"),
        NIC("NIC", "NI", "Nicarágua"),
        NER("NER", "NE", "Níger"),
        NGA("NGA", "NG", "Nigéria"),
        NIU("NIU", "NU", "Niue"),
        NOR("NOR", "NO", "Noruega"),
        NCL("NCL", "NC", "Nova Caledônia"),
        NZL("NZL", "NZ", "Nova Zelândia"),
        OMN("OMN", "OM", "Omã"),
        PLW("PLW", "PW", "Palau"),
        PAN("PAN", "PA", "Panamá"),
        PNG("PNG", "PG", "Papua-Nova Guiné"),
        PAK("PAK", "PK", "Paquistão"),
        PRY("PRY", "PY", "Paraguai"),
        PYF("PYF", "PF", "Polinésia Francesa"),
        POL("POL", "PL", "Polônia"),
        QAT("QAT", "QA", "Qatar"),
        KGZ("KGZ", "KG", "Quirguistão"),
        COD("COD", "CD", "Congo"),
        DOM("DOM", "DO", "República Dominicana"),
        CZE("CZE", "CZ", "República Tcheca"),
        ROM("ROM", "RO", "Romênia"),
        RWA("RWA", "RW", "Ruanda"),
        ESH("ESH", "EH", "Saara Ocidental"),
        ASM("ASM", "AS", "Samoa Americana"),
        WSM("WSM", "WS", "Samoa Ocidental"),
        SMR("SMR", "SM", "San Marino"),
        SHN("SHN", "SH", "Santa Helena"),
        LCA("LCA", "LC", "Santa Lúcia"),
        BLM("BLM", "BL", "São Bartolomeu"),
        KNA("KNA", "KN", "São Cristóvão e Névis"),
        MAF("MAF", "MF", "São Martim"),
        STP("STP", "ST", "São Tomé e Príncipe"),
        SEN("SEN", "SN", "Senegal"),
        SLE("SLE", "SL", "Serra Leoa"),
        SRB("SRB", "RS", "Sérvia"),
        SYR("SYR", "SY", "Síria"),
        SOM("SOM", "SO", "Somália"),
        LKA("LKA", "LK", "Sri Lanka"),
        SPM("SPM", "PM", "St. Pierre and Miquelon"),
        SWZ("SWZ", "SZ", "Suazilândia"),
        SDN("SDN", "SD", "Sudão"),
        SWE("SWE", "SE", "Suécia"),
        CHE("CHE", "CH", "Suíça"),
        SUR("SUR", "SR", "Suriname"),
        TJK("TJK", "TJ", "Tadjiquistão"),
        THA("THA", "TH", "Tailândia"),
        TWN("TWN", "TW", "Taiwan"),
        TZA("TZA", "TZ", "Tanzânia"),
        TMP("TMP", "TP", "Timor Leste"),
        TGO("TGO", "TG", "Togo"),
        TON("TON", "TO", "Tonga"),
        TTO("TTO", "TT", "Trinidad and Tobago"),
        TUN("TUN", "TN", "Tunísia"),
        TKM("TKM", "TM", "Turcomenistão"),
        TUR("TUR", "TR", "Turquia"),
        TUV("TUV", "TV", "Tuvalu"),
        UGA("UGA", "UG", "Uganda"),
        UZB("UZB", "UZ", "Uzbequistão"),
        VUT("VUT", "VU", "Vanuatu"),
        VAT("VAT", "VA", "Vaticano"),
        VNM("VNM", "VN", "Vietnã"),
        ZMB("ZMB", "ZM", "Zâmbia"),
        ZWE("ZWE", "ZW", "Zimbábue");

        private String name;
        private String threeDigitsCode;
        private String twoDigitsCode;

        Country(String threeDigitsCode, String twoDigitsCode, String name) {
            this.twoDigitsCode = twoDigitsCode;
            this.threeDigitsCode = threeDigitsCode;
            this.name = name;
        }

        public String getName() {
            return name;
        }

        public String getThreeDigitsCode() {
            return threeDigitsCode;
        }

        public String getTwoDigitsCode() {
            return twoDigitsCode;
        }
    };
}
